name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy: 
      matrix:
        include:
          - os: macos-latest
            commandUpdate: ./solipath cabal update
            commandTest: ./solipath cabal test
          - os: ubuntu-latest
            commandUpdate: ./solipath cabal update
            commandTest: ./solipath cabal test
          - os: windows-latest
            commandUpdate: .\solipath.bat cabal update
            commandTest: .\solipath.bat cabal test
    steps:
    - uses: actions/checkout@v2
    - name: Run update
      run: ${{matrix.commandUpdate}}
    - name: Run tests
      run ${{matrix.commandTest}}
