name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ${{matrix.os}}

    strategy: 
      matrix:
        include:
          - os: macos-latest
            command: ./solipath cabal update && ./solipath cabal test
          - os: ubuntu-latest
            command: ./solipath cabal update && ./solipath cabal test
          - os: windows-latest
            command: .\solipath cabal update && .\solipath.bat cabal test
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: ${{matrix.command}}
